### PR TITLE
Preparing release 2.0.0

### PR DESCRIPTION
**Pull request by glasserc**
**Step 1**
```
$ git co -b prepare-X.X
$ prerelease
$ vim docs/conf.py
$ git ci -a --amend
$ git push origin prepare-X.X
```

* [x] Merge remaining pull requests
* [x] Update changelog
* [x] Update version in docs/conf.py
* [x] Version dependencies

**Step 2**
```
$ git co master
$ git merge --no-ff prepare-X.X
$ release
$ postrelease
```
* [ ] Tag vX.Y.Z
* [ ] Publish on Pypi

**Step 3**
* [ ] Close milestone in Github
* [ ] Add entry in Github release page
* [ ] Create next milestone in Github
* [ ] Configure the version in ReadTheDocs
* [ ] Update kinto version in kinto.js repo
* [ ] Upgrade demo server
* [ ] Upgrade kinto-dist
* [ ] Send mail to ML
* [ ] Tweet!

@Natim @leplatrem r?

### CODE REVIEW

**Comment by Natim** [comment]
We should run the ``make build-requirements`` command.
I have created https://github.com/glasserc/kinto-fxa/pull/1 about that.

I think it could be better to upload you pull-request branch to the kinto or mozilla-services organization rather than your own fork so that we can collaborate on the PR branches.

**Comment by glasserc** [comment]
I've merged the PR that you opened. I noticed that some of the projects I was renaming definitely didn't have Makefiles or requirements.txt files, but I figured that if we got this far without them, then maybe we didn't need them :)

**Comment by Natim** [comment]
Yes probably but since you kept them in the PR release process I though it was a good thing to add them. It can help us to debug strange behavior if an version of an addon starts not to work anymore for isntance.

**Comment by Natim** [comment]
r+

**Pull request merged**
